package wob.city.newspaper.enums;

public enum Folder {
    CONSUMPTION_NEWS,
    DEATH_NEWS,
    NEW_BORN_NEWS,
    DISASTER_NEWS,
    CAUGHT_CRIMINAL_NEWS,
    ESCAPED_CRIMINAL_NEWS,
    SAVED_BY_FIREFIGHTER_NEWS,
    SAVED_BY_PARAMEDIC_NEWS,
    KILLED_BY_CRIMINAL_NEWS
}
